### ISSUE TITLE
eccodes_version.h is missing

### ISSUE THREAD

**Issue by jnyrup** [0x1mason/GribApi.XP#3]
When trying to build GribAPi.XP msbuild yells about it cannot find `eccodes_version.h`.
It seems to be left out on purpose in the `grib_api\.gitignore`?

Should this file be auto generated somehow?

**Comment by paulinodjm** [comment]
Got the same error, and I'm still not able to build the master.
Any update on this issue?

**Comment by adamsg69** [comment]
This file is apparently generated by the Linux build. I downloaded eccodes onto an ubuntu box, fllowed the build instructions there, the eccodes_version.h was generated as part of the Linux build. I copied the resulting file back onto my windows machine and the windows build succeeded.

**Comment by adamsg69** [comment]
For version 2.7.0 the content of the file is:
```
/*
 * Copyright 2005-2018 ECMWF.
 *
 * This software is licensed under the terms of the Apache Licence Version 2.0
 * which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
 *
 * In applying this licence, ECMWF does not waive the privileges and immunities granted to it by
 * virtue of its status as an intergovernmental organisation nor does it submit to any jurisdiction.
 */

#ifndef eccodes_version_H
#define eccodes_version_H

#define ECCODES_VERSION_STR      "2.7.0"

#define ECCODES_MAJOR_VERSION    2
#define ECCODES_MINOR_VERSION    7
#define ECCODES_REVISION_VERSION 0
#define ECCODES_VERSION (ECCODES_MAJOR_VERSION*10000+ECCODES_MINOR_VERSION*100+ECCODES_REVISION_VERSION)

#endif /* eccodes_version_H */
```

**Comment by jnyrup** [comment]
Thanks @adamsg69 that helped.

Here's a complete script of what I did.
```
cd build
cmake ../grib_api -DENABLE_FORTRAN=OFF -DENABLE_NETCDF=OFF -DENABLE_PYTHON=OFF -DENABLE_PNG=OFF -DENABLE_JPG=OFF
cp src/eccodes_version.h ../grib_api/src
```
